config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "webhooks#index"

  resources :webhooks, only: :index
  resources :events, only: :create
  resources :issues, only: [] do
    resources :events, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :repository
  validates :repository, :kind, :payload, presence: true
end

app/models/issue_event.rb
class IssueEvent < Event
  validates :external_id, presence: true
end

app/models/repository.rb
class Repository < ApplicationRecord
  has_many :events
  validates :external_id, :full_name, :html_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :json

  before_action :verify_signature!, only: :create
  skip_before_action :verify_authenticity_token, only: :create

  def index
    @events = IssueEvent.where(external_id: params[:issue_id])
    respond_with_paginated(@events)
  end

  def create
    set_repository!
    @repository.events.create!(event_params)
    render json: @repository
  end

  private

  def respond_with_paginated(collection)
    collection = collection.page(params[:page] || 1).
      per(params[:per_page] || 10).
      order(created_at: :desc)

    data = {
      current_page: collection.current_page,
      per_page: collection.limit_value,
      total_pages: collection.total_pages,
      total_count: collection.total_count
    }

    data[collection.table_name] = collection
    render json: data
  end

  def verify_signature!
    github_signature = request.env['HTTP_X_HUB_SIGNATURE']
    render json: 'Bad signature', status: :unauthorized if github_signature.blank? || !validate_signature(github_signature)
  end

  def validate_signature(github_signature)
    return unless ENV['SECRET_TOKEN']

    request.body.rewind
    payload_body = request.body.read
    signature = 'sha1=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), ENV['SECRET_TOKEN'], payload_body)
    Rack::Utils.secure_compare(signature, github_signature)
  end

  def set_repository!
    @repository = Repository.find_or_initialize_by(external_id: repository_params.delete(:id))
    return unless @repository.new_record?

    @repository.assign_attributes(repository_params)
    @repository.save
  end

  def repository_params
    params.require(:repository).permit(:id, :full_name, :description, :html_url)
  end

  def event_params
    attrs = { kind: request.env['HTTP_X_GITHUB_EVENT'], payload: params.permit!.to_h }

    if attrs[:kind] == "issues"
      attrs.merge!({
        external_id: params.fetch(:issue, {}).fetch(:id, nil),
        type: 'IssueEvent'
      })
    end

    attrs
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = Repository.all
    @secret_token = ENV['SECRET_TOKEN']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      <%= current_user.email %> | <%= link_to('Sign out', destroy_user_session_path, method: :delete) %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/webhooks/index.html.erb
<h1>Webhooks</h1>

<p>Github Payload URL: <span id="hook-url"><%= events_url %></span></p>
<p>Github secret token: <span id="secret-token"><%= @secret_token %></span></p>

<% if @repositories.exists? %>
  <h2> Configured Hooks for: </h2>

  <% @repositories.each do |repository| %>
    <br>
    <div id="repository-<%= repository.id %>">
      <div>Github ID: <%= repository.external_id %></div>
      <div>Repository: <%= repository.full_name %></div>
      <% if repository.description %>
        <div>Description: <%= repository.description %></div>
      <% end %>
      <div>Url: <%= link_to repository.html_url, repository.html_url %></div>
    </div>
  <% end %>
<% else %>
  You do not have configured hooks
<% end %>